import { ROLES } from './roles';

export const menuByRole = {
  [ROLES.SUPER_ADMIN]: [
    'Dashboard',
    'Company',
    'Runner’s User',
    'Task',
    'Client',
    'Employee',
    'Financial',
    'Document Management',
    'Generate Reports',
    'Property List',
    'Support',
    'Contract',
    'Subscription',
    // 'Roles Management',
    'Financial Management',
    // 'Mail',
    'Notification',
    'Settings',
    'Templates',
    'Chat',
    'Employee Payment',
  ],

  [ROLES.COMPANY_ADMIN]: [
    'Dashboard',
    'Offer',
    'Task',
    'Client',
    'Group',
    'Property List',
    'Employee',
    'Financial Management',
    'Document Management',
    'Generate Reports',
    'Support',
    'Contract',
    'Notification',
    'Profile',
    'Chat',
    'Settings',
    'Templates',
    'Invoice',
    'Employee Payment',
  ],

  [ROLES.GROUP_ADMIN]: [
    'Dashboard',
    'Task',
    'Contract List',
    'Document Management',
    'Generate Reports',
    'Property List',
    'Support',
    'Notification',
    'Chat',
  ],

  [ROLES.EMPLOYEE]: [
    'Dashboard',
    'Task',
    'Support',
    'Chat',
    'Calendar',
    'Notification',
    'Financial',
    'Settings',
  ],
  [ROLES.FINANCE_MANAGER]: [
    'Dashboard',
    'Marketplace',
    'Accounting',
    'Receivables',
    'Payables',
    'Company Finance Overview',
    'VAT',
    'Financial Statements',
    'Payroll',
    'Analytics',
    'Task & Cost',
    'Finance Settings',
    'Notification',
    'Chat',
    'Settings',
  ],
};

