// role-permissions.js
import { ROLES } from './roles';
import { PERMISSIONS } from './permissions';

export const ROLE_PERMISSIONS = {
  // ───────────── Super Admin ─────────────
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  // ───────────── Company Admin ─────────────
  [ROLES.COMPANY_ADMIN]: [
    // Dashboard
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_ANALYTICS,

    // Company
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_CREATE,
    PERMISSIONS.COMPANY_UPDATE,

    // Users
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_ASSIGN_ROLE,

    // Contracts
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.CONTRACT_CREATE,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_SEND,

    // Tasks
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_REPORT,

    // Documents
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_VIEW,

    // Finance
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_EXPORT,

    // Support / Chat
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_CREATE,
    PERMISSIONS.CHAT_VIEW,

    // Groups
    PERMISSIONS.GROUP_VIEW,
    PERMISSIONS.GROUP_CREATE,
  ],

  // ───────────── Group Admin ─────────────
  [ROLES.GROUP_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_REPORT,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.GROUP_VIEW,
    PERMISSIONS.GROUP_CREATE,
  ],

  // ───────────── Finance Manager ─────────────
  [ROLES.FINANCE_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_ANALYTICS,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.FINANCE_EXPORT,
  ],

  // ───────────── Employee ─────────────
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_START,
    PERMISSIONS.TASK_END,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.CHAT_VIEW,
  ],
};
